### ISSUE TITLE
dueros failed but alexa works well

### ISSUE THREAD

**Issue by fellylanma** [respeaker/avs#2]
Hi, I tryed your project and the alexa part works well , and i change it to dueros, and successfully get the .avs.json of dueros, alexa-auth runs successfully. but when i run the alexa-tap, some thing went wrong .
the errors are like:

DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present
ERROR:avs.alexa:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/avs-0.0.4-py2.7.egg/avs/alexa.py", line 83, in loop
    self._loop()
  File "/usr/lib/python2.7/site-packages/avs-0.0.4-py2.7.egg/avs/alexa.py", line 102, in _loop
    downchannel_response = conn.get_response(downchannel_id)
  File "/usr/lib/python2.7/site-packages/hyper/http20/connection.py", line 312, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/usr/lib/python2.7/site-packages/hyper/http20/stream.py", line 230, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/usr/lib/python2.7/site-packages/hyper/http20/connection.py", line 771, in _recv_cb
    self._single_read()
  File "/usr/lib/python2.7/site-packages/hyper/http20/connection.py", line 665, in _single_read
    self._sock.fill()
  File "/usr/lib/python2.7/site-packages/hyper/common/bufsocket.py", line 169, in fill
    raise ConnectionResetError()
ConnectionResetError
INFO:avs.alexa:reconnect...
DEBUG:hyper.http20.connection:Selected NPN protocol: h2
DEBUG:hyper.http20.connection:recv for stream 0 with set([]) already present
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x1444be0>
DEBUG:hpack.hpack:Adding (':method', 'GET') to the header table
DEBUG:hpack.hpack:Encoding 2 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'dueros-h2.baidu.com') to the header table
DEBUG:hpack.hpack:Encoding 1 with 6 bits
DEBUG:hpack.hpack:Encoding 14 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/dcs/avs-compatible-v20160207/directives') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 28 with 7 bits
DEBUG:hpack.hpack:Adding ('dueros-device-id', '9913590') to the header table
DEBUG:hpack.hpack:Encoding 12 with 7 bits
DEBUG:hpack.hpack:Encoding 5 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer 21.d6ddc4ba0a04ec75807b1d7670f6adcc.2592000.1503209501.1044836695-9913590') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 56 with 7 bits
DEBUG:hpack.hpack:Encoded header block t

as baidu says dueros is compatible with  avs, and i'm confused about the result.
maybe the only reason is that dueros does not support NPN, only support ALPN

seeking for help, thanks.

here are my .avs.json
{
    "product_id": "9913590",
    "access_token": "21.d6ddc4ba0a04ec75807b1d7670f6adcc.2592000.1503209501.1044836695-9913590",
    "expiry": "Sun Aug 20 06:11:41 2017",
    "client_id": "YqjHUWjMyDq5gXlpFmxI6TfOwZLUS2qs",
    "host_url": "dueros-h2.baidu.com",
    "client_secret": "3SQku25Gtp0ROv2Nuz1NU9kGChgWNHjc",
    "refresh_token": "22.5dd801f948ef763dc6855e76c6147fbd.315360000.1815977501.1044836695-9913590",
    "dueros-device-id": "9913590"
}

**Comment by xiongyihui** [comment]
On my computer, your tokens works. The log is

```
DEBUG:hyper.http20.connection:Selected NPN protocol: h2
DEBUG:hyper.http20.connection:recv for stream 0 with set([]) already present
INFO:hyper.http20.connection:Received unhandled event <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=10), ChangedSetting(setting=SettingCodes._max_frame_size, original_value=16384, new_value=1048576), ChangedSetting(setting=SettingCodes._max_header_list_size, original_value=None, new_value=1048896)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{}>
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x7f18e06da960>
DEBUG:hpack.hpack:Adding (':method', 'GET') to the header table
DEBUG:hpack.hpack:Encoding 2 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'dueros-h2.baidu.com') to the header table
DEBUG:hpack.hpack:Encoding 1 with 6 bits
DEBUG:hpack.hpack:Encoding 14 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/dcs/avs-compatible-v20160207/directives') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 28 with 7 bits
DEBUG:hpack.hpack:Adding ('dueros-device-id', '9913590') to the header table
DEBUG:hpack.hpack:Encoding 12 with 7 bits
DEBUG:hpack.hpack:Encoding 5 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer 21.d6ddc4ba0a04ec75807b1d7670f6adcc.2592000.1503209501.1044836695-9913590') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 56 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ��A����t-8��f���zD�bB!��B�=5�&����@
                                                                             �bCXR$�ʏ@����t-!{��X��}�����Q�[W��$#Q�E#��c
                                                                                                                        ���%pr����p�D�▒i�\q��}����
DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present
DEBUG:hpack.hpack:Decoding ?�H403a��i~�je�����˗}LZ7�@���g�[
                                                           "������
�_�I|�����P���0Z�V{\5
DEBUG:hpack.hpack:Decoded 4096, consumed 3 bytes
DEBUG:hpack.table:Resizing header table to 4096 from 4096
DEBUG:hpack.hpack:Decoded 8, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 3, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', <memory at 0x7f18ddb182b0>), total consumed 5 bytes, indexed True
DEBUG:hpack.hpack:Decoded 33, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 23, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('date', 'Tue, 25 Jul 2017 07:36:39 GMT'), total consumed 25 bytes, indexed True
DEBUG:hpack.hpack:Decoded 9, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 6, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-powered-by', 'Express'), total consumed 18 bytes, indexed True
DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 18, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-type', 'text/plain; charset=utf-8'), total consumed 20 bytes, indexed True
DEBUG:hpack.hpack:Decoded 28, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 1, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-length', <memory at 0x7f18ddb18218>), total consumed 3 bytes, indexed True
ERROR:__main__:/directive requests returned 403
Traceback (most recent call last):
  File "/home/i/lab/alexa_voice_service/avs/alexa.py", line 86, in loop
    self._loop()
  File "/home/i/lab/alexa_voice_service/avs/alexa.py", line 107, in _loop
    raise ValueError("/directive requests returned {}".format(downchannel_response.status))
ValueError: /directive requests returned 403
INFO:__main__:reconnect...
DEBUG:hyper.http20.connection:Selected NPN protocol: h2
DEBUG:hyper.http20.connection:recv for stream 0 with set([]) already present
INFO:hyper.http20.connection:Received unhandled event <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=10), ChangedSetting(setting=SettingCodes._max_frame_size, original_value=16384, new_value=1048576), ChangedSetting(setting=SettingCodes._max_header_list_size, original_value=None, new_value=1048896)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{}>
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x7f18ddb37140>
DEBUG:hpack.hpack:Adding (':method', 'GET') to the header table
DEBUG:hpack.hpack:Encoding 2 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'dueros-h2.baidu.com') to the header table
DEBUG:hpack.hpack:Encoding 1 with 6 bits
DEBUG:hpack.hpack:Encoding 14 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/dcs/avs-compatible-v20160207/directives') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 28 with 7 bits
DEBUG:hpack.hpack:Adding ('dueros-device-id', '9913590') to the header table
DEBUG:hpack.hpack:Encoding 12 with 7 bits
DEBUG:hpack.hpack:Encoding 5 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer 21.d6ddc4ba0a04ec75807b1d7670f6adcc.2592000.1503209501.1044836695-9913590') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 56 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ��A����t-8��f���zD�bB!��B�=5�&����@
                                                                             �bCXR$�ʏ@����t-!{��X��}�����Q�[W��$#Q�E#��c
                                                                                                                        ���%pr����p�D�▒i�\q��}����
DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present
&=LtA�a��i~�je�����˗▒��o@����%Y��l��bX��
                                  �.�+���       �@���g�[
                                                        "������
�
DEBUG:hpack.hpack:Decoded 4096, consumed 3 bytes
DEBUG:hpack.table:Resizing header table to 4096 from 4096
DEBUG:hpack.hpack:Decoded 8, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', '200'), consumed 1
DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 54, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-type', 'multipart/related; boundary=___dumi_avs_xuejuntao___; type=application/json'), total consumed 56 bytes, indexed True
DEBUG:hpack.hpack:Decoded 33, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 22, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('date', 'Tue, 25 Jul 2017 07:36:40 GMT'), total consumed 24 bytes, indexed True
DEBUG:hpack.hpack:Decoded 9, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 13, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('remote-server', '10.194.63.28:8280'), total consumed 25 bytes, indexed True
DEBUG:hpack.hpack:Decoded 9, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 6, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-powered-by', 'Express'), total consumed 18 bytes, indexed True
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0x7f18ddb3d190>
DEBUG:hpack.hpack:Adding (':method', 'POST') to the header table
DEBUG:hpack.hpack:Encoding 3 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'dueros-h2.baidu.com') to the header table
DEBUG:hpack.hpack:Encoding 64 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/dcs/avs-compatible-v20160207/events') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 25 with 7 bits
DEBUG:hpack.hpack:Adding ('dueros-device-id', '9913590') to the header table
DEBUG:hpack.hpack:Encoding 63 with 7 bits
DEBUG:hpack.hpack:Adding ('content-type', 'multipart/form-data; boundary=seeed-voice-engine') to the header table
DEBUG:hpack.hpack:Encoding 31 with 6 bits
DEBUG:hpack.hpack:Encoding 34 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer 21.d6ddc4ba0a04ec75807b1d7670f6adcc.2592000.1503209501.1044836695-9913590') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 56 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ���D�bB!��B�=5�&����@
                                                               �`��RQ�_���j�bX��R��H�Ԍ�� ��
Rȷs��X�Lj��Q�[W��$#Q�E#��c
                          ���%pr����p�D�▒i�\q��}����
DEBUG:__main__:metadata: {
    "event": {
        "header": {
            "namespace": "System", 
            "name": "SynchronizeState", 
            "messageId": "1699ef814b8d4814807a6f8390e4b095"
        }, 
        "payload": {}
    }, 
    "context": [
        {
            "header": {
                "namespace": "SpeechSynthesizer", 
                "name": "SpeechState"
            }, 
            "payload": {
                "token": "", 
                "playerActivity": "FINISHED", 
                "offsetInMilliseconds": 0
            }
        }, 
        {
            "header": {
                "namespace": "Speaker", 
                "name": "VolumeState"
            }, 
            "payload": {
                "volume": 50, 
                "muted": false
            }
        }, 
        {
            "header": {
                "namespace": "AudioPlayer", 
                "name": "PlaybackState"
            }, 
            "payload": {
                "token": "", 
                "playerActivity": "IDLE", 
                "offsetInMilliseconds": 0
            }
        }
    ]
}
INFO:__main__:wait for response
DEBUG:hyper.http20.connection:recv for stream 3 with set([1]) already present
press ENTER to talk
INFO:hyper.http20.connection:Received unhandled event <WindowUpdated stream_id:0, delta:675>
INFO:hyper.http20.connection:Received unhandled event <WindowUpdated stream_id:0, delta:24>
DEBUG:hyper.http20.connection:recv for stream 3 with set([1]) already present
DEBUG:hpack.hpack:Decoding �_���j�bX��R��H�Ԍ�� ��QE%��!�D^m/KjH�Q��
DEBUG:hpack.hpack:Decoded 9, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', '204'), consumed 1
DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 40, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-type', 'multipart/form-data; boundary=___dumi_avs_xuejuntao___'), total consumed 42 bytes, indexed True
DEBUG:hpack.hpack:Decoded 65, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('date', 'Tue, 25 Jul 2017 07:36:40 GMT'), consumed 1
DEBUG:hpack.hpack:Decoded 63, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-powered-by', 'Express'), consumed 1
INFO:__main__:status code: 204
```

**Comment by xiongyihui** [comment]
It seems it's a problem of NPN. When I try it on a new device, it can't work without installing `python-openssl`.

The http2 library `hyper` will prefer to use ALPN when openssh is available.

**Comment by xiongyihui** [comment]
A note from Lukasa

>ALPN was added in OpenSSL 1.0.2

https://github.com/Lukasa/hyper/issues/213#issuecomment-200440611
