### ISSUE TITLE
can't detect gstreamer or mpg123 or mpv

### ISSUE THREAD

**Issue by greggameplayer** [respeaker/avs#25]
* Python Alexa Voice Service version: 0.5.3
* Python version: 3.6 & 2.7.15 (Kind of same thing)
* Operating System: Windows 10

### Description

I was trying to do the audio check but it don't detect mpg123, mpv which i've install

### What I Did

```
alexa-audio-check

Le chemin d’accès spécifié est introuvable.
Le chemin d’accès spécifié est introuvable.
Le chemin d’accès spécifié est introuvable.
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\avs\player\__init__.py", line 21, in <module>
    from .gstreamer_player import Player
  File "c:\program files (x86)\python36-32\lib\site-packages\avs\player\gstreamer_player.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\alexa-audio-check.exe\__main__.py", line 5, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\avs\check.py", line 15, in <module>
    from avs.player import Player
  File "c:\program files (x86)\python36-32\lib\site-packages\avs\player\__init__.py", line 28, in <module>
    raise ImportError('No player available, install one of the players: gstreamer, mpv and mpg123 first')
ImportError: No player available, install one of the players: gstreamer, mpv and mpg123 first

```

**Comment by xiongyihui** [comment]
I have not tested it on Windows. Maybe `mpg123` or `mpv` is not your system PATH.
