### ISSUE TITLE
a problem cuased by pyaudio

### ISSUE THREAD

**Issue by Curricane** [respeaker/avs#30]
* Python Alexa Voice Service version:
* Python version:3.6.7
* Operating System:Ubuntu 16

### Description

Describe what you were trying to get done.
iat last,when a run "alexa", it told me that :
(py3) zz@zz:~/py3/avs$ alexa
Traceback (most recent call last):
  File "/usr/local/bin/alexa", line 11, in <module>
    load_entry_point('avs==0.5.4', 'console_scripts', 'alexa')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/avs-0.5.4-py3.6.egg/avs/main.py", line 22, in <module>
    from respeaker.pixel_ring import pixel_ring
  File "/usr/local/lib/python3.6/dist-packages/respeaker/__init__.py", line 18, in <module>
    from respeaker.microphone import Microphone
  File "/usr/local/lib/python3.6/dist-packages/respeaker/microphone.py", line 33, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by xiongyihui** [comment]
It seems pyaudio is not installed. To install it, run `sudo apt install python3-pyaudio` or `sudo pip3 install pyaudio`
