### ISSUE TITLE
Ubuntu 17.10 , no go

### ISSUE THREAD

**Issue by Zibri** [respeaker/avs#33]
$ alexa-auth -c config.json
Traceback (most recent call last):
  File "/usr/local/bin/alexa-auth", line 11, in <module>
    load_entry_point('avs==0.5.4', 'console_scripts', 'alexa-auth')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/avs-0.5.4-py2.7.egg/avs/auth.py", line 9, in <module>
    import tornado.httpserver
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0a1-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 144
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax

**Comment by Songwaitter** [comment]
I have resolved this issue.reinstall tornado
commond:
pip uninstall tornado
pip install --upgrade pip
pip install tornado

**Comment by Songwaitter** [comment]
I have resolved this issue.reinstall tornado
commond:
`pip uninstall tornado
pip install --upgrade pip
pip install tornado`

**Comment by Songwaitter** [comment]
I have resoved this issuse
commoand
```
pip uninstall tornado
pip install --upgrade pip
pip install tornado
```

**Comment by Zibri** [comment]
$ alexa-auth
Traceback (most recent call last):
  File "/usr/local/bin/alexa-auth", line 6, in <module>
    from avs.auth import main
  File "/usr/local/lib/python3.6/dist-packages/avs/auth.py", line 16, in <module>
    class MainHandler(tornado.web.RequestHandler):
  File "/usr/local/lib/python3.6/dist-packages/avs/auth.py", line 21, in MainHandler
    @tornado.web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by Zibri** [comment]
I solved this by doing:

sudo pip3 uninstall "tornado"
sudo pip3 install -I "tornado<6"

Because that is a bug of tornado >=6

After adding the return url to alexa account I started alexa-tap
But I continue getting errors..


```
press ENTER to talk
INFO:hyper.http20.connection:Received unhandled event <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=2147483647), ChangedSetting(setting=SettingCodes._max_header_list_size, original_value=None, new_value=40960)}>
INFO:hyper.http20.connection:Received unhandled event <WindowUpdated stream_id:0, delta:2147418112>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{}>
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:1, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:wait for response
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:3, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:status code: 200
INFO:avs.alexa:{
    "header": {
        "namespace": "System",
        "name": "SetEndpoint",
        "messageId": "1bbdcb15-e3a8-4883-b252-e59cefc4aef3"
    },
    "payload": {
        "endpoint": "https://avs-alexa-eu.amazon.com"
    }
}
INFO:avs.alexa:on_ready

INFO:avs.alexa:on_listening
press ENTER to talk

press ENTER to talk
INFO:avs.alexa:{
    "header": {
        "namespace": "SpeechRecognizer",
        "name": "StopCapture",
        "messageId": "0861c98c-d1bf-4bcc-a1e8-7d68d63ee3e8",
        "dialogRequestId": "c5aa8bf3a9624556a4f34918d03f6db8"
    },
    "payload": {}
}
INFO:SpeechRecognizer:StopCapture
INFO:avs.alexa:on_thinking
INFO:avs.alexa:wait for response
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:5, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:status code: 200
INFO:avs.alexa:{
    "header": {
        "namespace": "System",
        "name": "SetEndpoint",
        "messageId": "a19a97be-0011-4fa4-9a5f-00f3d1133887",
        "dialogRequestId": "c5aa8bf3a9624556a4f34918d03f6db8"
    },
    "payload": {
        "endpoint": "https://avs-alexa-eu.amazon.com"
    }
}
INFO:SpeechRecognizer:conversation = 0
INFO:avs.alexa:on_finished

INFO:avs.alexa:on_listening
press ENTER to talk

press ENTER to talk
INFO:avs.alexa:{
    "header": {
        "namespace": "SpeechRecognizer",
        "name": "StopCapture",
        "messageId": "f087e0ef-1434-4200-af78-a26b2b239899",
        "dialogRequestId": "c787143f5077467ab58e44ff75fc9092"
    },
    "payload": {}
}
INFO:SpeechRecognizer:StopCapture
INFO:avs.alexa:on_thinking
INFO:avs.alexa:wait for response
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:7, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:status code: 200
INFO:avs.alexa:{
    "header": {
        "namespace": "System",
        "name": "SetEndpoint",
        "messageId": "2c8e28a5-1e67-45c7-b0f7-6396ff254807",
        "dialogRequestId": "c787143f5077467ab58e44ff75fc9092"
    },
    "payload": {
        "endpoint": "https://avs-alexa-eu.amazon.com"
    }
}
INFO:SpeechRecognizer:conversation = 0
INFO:avs.alexa:on_finished

```
