### ISSUE TITLE
Problems with alexa-auth

### ISSUE THREAD

**Issue by lilitsve** [respeaker/avs#35]
### Description
I followed the README instructions, but alexa-auth command line is not working as expected 

### What I Did

```
alexa-auth
```
I obtained the following issues : 
```
Traceback (most recent call last):
  File "/home/lilitsve/.local/bin/alexa-auth", line 7, in <module>
    from avs.auth import main
  File "/home/lilitsve/.local/lib/python2.7/site-packages/avs/auth.py", line 9, in <module>
    import tornado.httpserver
  File "/home/lilitsve/.local/lib/python2.7/site-packages/tornado/httpserver.py", line 144
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax
```
Please, can you help me, I'm struggling with  this issue?

**Comment by lilitsve** [comment]
I solved it. 
In fact, I have the Respeaker Mic Array v2.0, so I had to follow the instructions as if I had the Respeaker Core. So, if you use the mic array, skip the "For Debian/Ubuntu/Raspbian" part in the wiki !!!
